#!/usr/bin/env node

const fs = require('fs');
const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

console.log('🔑 Document Scanner API Key Setup');
console.log('================================\n');

console.log('This script will help you set up your Google Cloud Vision API key.');
console.log('Get your API key from: https://console.cloud.google.com/apis/credentials\n');

rl.question('Enter your Google Cloud Vision API key: ', (apiKey) => {
  if (!apiKey || apiKey.trim() === '') {
    console.log('❌ No API key provided. Please run this script again with a valid API key.');
    rl.close();
    return;
  }

  // Validate API key format (Google API keys start with AIza)
  if (!apiKey.startsWith('AIza')) {
    console.log('⚠️  Warning: This doesn\'t look like a Google API key (should start with "AIza")');
    console.log('   Please verify you copied the correct key from Google Cloud Console.');
  }

  // Create .env file
  const envContent = `# Google Cloud Vision API Key
# Generated by setup-api-key.js
EXPO_PUBLIC_OCR_API_KEY=${apiKey.trim()}

# App Configuration
EXPO_PUBLIC_APP_ENV=production
EXPO_PUBLIC_DEBUG_MODE=false
`;

  try {
    fs.writeFileSync('.env', envContent);
    console.log('✅ .env file created successfully!');
    console.log('✅ API key configured for Document Scanner');
    console.log('\n📋 Next steps:');
    console.log('1. Test your app: npx expo start --clear');
    console.log('2. Open camera screen and scan a document');
    console.log('3. Check console for OCR results');
    console.log('\n🔒 Security reminder:');
    console.log('- Never commit .env file to git');
    console.log('- Add .env to your .gitignore file');
    console.log('- Keep your API key secure');
  } catch (error) {
    console.error('❌ Error creating .env file:', error.message);
  }

  rl.close();
});

rl.on('close', () => {
  console.log('\n🎉 Setup complete! Your Document Scanner is ready to use OCR.');
  process.exit(0);
});
