import React, { useState, useEffect } from 'react';
import {
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
  ScrollView,
  Alert,
  ActivityIndicator,
  Dimensions,
} from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { Ionicons } from '@expo/vector-icons';
import { AIAutoCropping, AICropResult } from '../utils/aiAutoCropping';
import { AIDocumentClassification, DocumentClassificationResult } from '../utils/aiDocumentClassification';
import { AISmartOrganization, DocumentMetadata, OrganizationResult, SmartTag } from '../utils/aiSmartOrganization';
import { AIQualityAssessment, QualityAssessmentResult, ImprovementSuggestion } from '../utils/aiQualityAssessment';

const { width } = Dimensions.get('window');

interface AIEnhancementsPanelProps {
  visible: boolean;
  imageUri: string;
  onClose: () => void;
  onEnhancementComplete: (result: any) => void;
  documentMetadata?: DocumentMetadata;
}

const AIEnhancementsPanel: React.FC<AIEnhancementsPanelProps> = ({
  visible,
  imageUri,
  onClose,
  onEnhancementComplete,
  documentMetadata
}) => {
  const [activeTab, setActiveTab] = useState<'cropping' | 'classification' | 'organization' | 'quality'>('cropping');
  const [isProcessing, setIsProcessing] = useState(false);
  const [processingStep, setProcessingStep] = useState('');
  
  // AI Services
  const [aiCropping] = useState(() => AIAutoCropping.getInstance());
  const [aiClassification] = useState(() => AIDocumentClassification.getInstance());
  const [aiOrganization] = useState(() => AISmartOrganization.getInstance());
  const [aiQuality] = useState(() => AIQualityAssessment.getInstance());
  
  // Results
  const [cropResult, setCropResult] = useState<AICropResult | null>(null);
  const [classificationResult, setClassificationResult] = useState<DocumentClassificationResult | null>(null);
  const [organizationResult, setOrganizationResult] = useState<OrganizationResult | null>(null);
  const [qualityResult, setQualityResult] = useState<QualityAssessmentResult | null>(null);

  useEffect(() => {
    if (visible && imageUri) {
      runAllAIEnhancements();
    }
  }, [visible, imageUri]);

  const runAllAIEnhancements = async () => {
    setIsProcessing(true);
    
    try {
      // Step 1: AI Auto-cropping
      setProcessingStep('Applying AI auto-cropping...');
      const crop = await aiCropping.performAICropping(imageUri, {
        enableSmartCrop: true,
        preserveAspectRatio: true,
        confidenceThreshold: 0.7
      });
      setCropResult(crop);

      // Step 2: Document Classification
      setProcessingStep('Classifying document type...');
      const classification = await aiClassification.classizeDocument(crop.croppedUri, {
        enableSubclassification: true,
        extractMetadata: true,
        generateTags: true
      });
      setClassificationResult(classification);

      // Step 3: Quality Assessment
      setProcessingStep('Assessing document quality...');
      const quality = await aiQuality.assessQuality(crop.croppedUri, {
        enableDetailedAnalysis: true,
        generateSuggestions: true,
        includeAutomatedFixes: true
      });
      setQualityResult(quality);

      // Step 4: Smart Organization (if metadata provided)
      if (documentMetadata) {
        setProcessingStep('Organizing document...');
        const organization = await aiOrganization.organizeDocuments([{
          ...documentMetadata,
          uri: crop.croppedUri,
          documentType: classification.documentType,
          qualityScore: quality.metrics.overall,
          tags: classification.tags.map(tag => ({
            id: tag,
            name: tag,
            category: 'content' as const,
            confidence: 0.8,
            autoGenerated: true,
            color: '#2196F3'
          }))
        }]);
        setOrganizationResult(organization);
      }

      setProcessingStep('AI enhancements complete!');
      
      // Notify parent component
      onEnhancementComplete({
        crop: crop,
        classification: classification,
        quality: quality,
        organization: organizationResult
      });

    } catch (error) {
      console.error('AI enhancements failed:', error);
      Alert.alert('Error', 'AI enhancements failed. Please try again.');
    } finally {
      setIsProcessing(false);
      setProcessingStep('');
    }
  };

  const renderTabButton = (tab: string, icon: string, label: string) => (
    <TouchableOpacity
      style={[
        styles.tabButton,
        activeTab === tab && styles.activeTabButton
      ]}
      onPress={() => setActiveTab(tab as any)}
    >
      <Ionicons 
        name={icon as any} 
        size={20} 
        color={activeTab === tab ? '#FFFFFF' : '#666666'} 
      />
      <Text style={[
        styles.tabButtonText,
        activeTab === tab && styles.activeTabButtonText
      ]}>
        {label}
      </Text>
    </TouchableOpacity>
  );

  const renderCroppingTab = () => (
    <ScrollView style={styles.tabContent}>
      {cropResult ? (
        <View>
          <View style={styles.resultHeader}>
            <Ionicons name="crop" size={24} color="#4CAF50" />
            <Text style={styles.resultTitle}>AI Auto-Cropping Results</Text>
          </View>
          
          <View style={styles.metricCard}>
            <Text style={styles.metricLabel}>Confidence</Text>
            <Text style={styles.metricValue}>{Math.round(cropResult.confidence * 100)}%</Text>
          </View>
          
          <View style={styles.metricCard}>
            <Text style={styles.metricLabel}>Document Type</Text>
            <Text style={styles.metricValue}>{cropResult.documentType}</Text>
          </View>
          
          <View style={styles.metricCard}>
            <Text style={styles.metricLabel}>Quality Score</Text>
            <Text style={styles.metricValue}>{Math.round(cropResult.qualityScore * 100)}%</Text>
          </View>

          {cropResult.suggestions.length > 0 && (
            <View style={styles.suggestionsCard}>
              <Text style={styles.suggestionsTitle}>Suggestions</Text>
              {cropResult.suggestions.map((suggestion, index) => (
                <Text key={index} style={styles.suggestionText}>• {suggestion}</Text>
              ))}
            </View>
          )}
        </View>
      ) : (
        <View style={styles.placeholder}>
          <ActivityIndicator size="large" color="#4CAF50" />
          <Text style={styles.placeholderText}>Processing AI auto-cropping...</Text>
        </View>
      )}
    </ScrollView>
  );

  const renderClassificationTab = () => (
    <ScrollView style={styles.tabContent}>
      {classificationResult ? (
        <View>
          <View style={styles.resultHeader}>
            <Ionicons name="document-text" size={24} color="#2196F3" />
            <Text style={styles.resultTitle}>Document Classification</Text>
          </View>
          
          <View style={styles.metricCard}>
            <Text style={styles.metricLabel}>Document Type</Text>
            <Text style={styles.metricValue}>{classificationResult.documentType}</Text>
          </View>
          
          {classificationResult.subcategory && (
            <View style={styles.metricCard}>
              <Text style={styles.metricLabel}>Subcategory</Text>
              <Text style={styles.metricValue}>{classificationResult.subcategory}</Text>
            </View>
          )}
          
          <View style={styles.metricCard}>
            <Text style={styles.metricLabel}>Confidence</Text>
            <Text style={styles.metricValue}>{Math.round(classificationResult.confidence * 100)}%</Text>
          </View>

          <View style={styles.featuresCard}>
            <Text style={styles.featuresTitle}>Detected Features</Text>
            <View style={styles.featuresGrid}>
              {Object.entries(classificationResult.features).map(([key, value]) => (
                <View key={key} style={styles.featureItem}>
                  <Text style={styles.featureLabel}>{key.replace(/([A-Z])/g, ' $1').toLowerCase()}</Text>
                  <Text style={styles.featureValue}>
                    {typeof value === 'boolean' ? (value ? 'Yes' : 'No') : 
                     typeof value === 'number' ? Math.round(value * 100) + '%' : value}
                  </Text>
                </View>
              ))}
            </View>
          </View>

          {classificationResult.tags.length > 0 && (
            <View style={styles.tagsCard}>
              <Text style={styles.tagsTitle}>AI Generated Tags</Text>
              <View style={styles.tagsContainer}>
                {classificationResult.tags.map((tag, index) => (
                  <View key={index} style={styles.tag}>
                    <Text style={styles.tagText}>{tag}</Text>
                  </View>
                ))}
              </View>
            </View>
          )}
        </View>
      ) : (
        <View style={styles.placeholder}>
          <ActivityIndicator size="large" color="#2196F3" />
          <Text style={styles.placeholderText}>Classifying document...</Text>
        </View>
      )}
    </ScrollView>
  );

  const renderOrganizationTab = () => (
    <ScrollView style={styles.tabContent}>
      {organizationResult ? (
        <View>
          <View style={styles.resultHeader}>
            <Ionicons name="folder" size={24} color="#9C27B0" />
            <Text style={styles.resultTitle}>Smart Organization</Text>
          </View>
          
          <View style={styles.metricCard}>
            <Text style={styles.metricLabel}>Documents Organized</Text>
            <Text style={styles.metricValue}>{organizationResult.organizedDocuments.length}</Text>
          </View>
          
          <View style={styles.metricCard}>
            <Text style={styles.metricLabel}>Rules Applied</Text>
            <Text style={styles.metricValue}>{organizationResult.appliedRules.length}</Text>
          </View>
          
          <View style={styles.metricCard}>
            <Text style={styles.metricLabel}>Folders Created</Text>
            <Text style={styles.metricValue}>{organizationResult.createdFolders.length}</Text>
          </View>

          {organizationResult.organizedDocuments.length > 0 && (
            <View style={styles.documentsCard}>
              <Text style={styles.documentsTitle}>Organized Documents</Text>
              {organizationResult.organizedDocuments.map((doc, index) => (
                <View key={index} style={styles.documentItem}>
                  <Text style={styles.documentName}>{doc.fileName}</Text>
                  <Text style={styles.documentPath}>{doc.organizationPath}</Text>
                  <View style={styles.documentTags}>
                    {doc.tags.slice(0, 3).map((tag, tagIndex) => (
                      <View key={tagIndex} style={[styles.documentTag, { backgroundColor: tag.color }]}>
                        <Text style={styles.documentTagText}>{tag.name}</Text>
                      </View>
                    ))}
                  </View>
                </View>
              ))}
            </View>
          )}

          {organizationResult.suggestions.length > 0 && (
            <View style={styles.suggestionsCard}>
              <Text style={styles.suggestionsTitle}>Organization Suggestions</Text>
              {organizationResult.suggestions.map((suggestion, index) => (
                <Text key={index} style={styles.suggestionText}>• {suggestion}</Text>
              ))}
            </View>
          )}
        </View>
      ) : (
        <View style={styles.placeholder}>
          <ActivityIndicator size="large" color="#9C27B0" />
          <Text style={styles.placeholderText}>Organizing document...</Text>
        </View>
      )}
    </ScrollView>
  );

  const renderQualityTab = () => (
    <ScrollView style={styles.tabContent}>
      {qualityResult ? (
        <View>
          <View style={styles.resultHeader}>
            <Ionicons name="analytics" size={24} color="#FF9800" />
            <Text style={styles.resultTitle}>Quality Assessment</Text>
          </View>
          
          <View style={styles.gradeCard}>
            <Text style={styles.gradeLabel}>Overall Grade</Text>
            <Text style={[styles.gradeValue, { color: getGradeColor(qualityResult.overallGrade) }]}>
              {qualityResult.overallGrade}
            </Text>
          </View>
          
          <View style={styles.metricsGrid}>
            {Object.entries(qualityResult.metrics).map(([key, value]) => (
              <View key={key} style={styles.metricItem}>
                <Text style={styles.metricItemLabel}>
                  {key.replace(/([A-Z])/g, ' $1').toLowerCase()}
                </Text>
                <View style={styles.metricBar}>
                  <View 
                    style={[
                      styles.metricBarFill, 
                      { width: `${value * 100}%`, backgroundColor: getMetricColor(value) }
                    ]} 
                  />
                </View>
                <Text style={styles.metricItemValue}>{Math.round(value * 100)}%</Text>
              </View>
            ))}
          </View>

          {qualityResult.issues.length > 0 && (
            <View style={styles.issuesCard}>
              <Text style={styles.issuesTitle}>Quality Issues</Text>
              {qualityResult.issues.map((issue, index) => (
                <View key={index} style={styles.issueItem}>
                  <View style={[styles.issueSeverity, { backgroundColor: getSeverityColor(issue.severity) }]} />
                  <View style={styles.issueContent}>
                    <Text style={styles.issueTitle}>{issue.description}</Text>
                    <Text style={styles.issueImpact}>{issue.impact}</Text>
                  </View>
                </View>
              ))}
            </View>
          )}

          {qualityResult.suggestions.length > 0 && (
            <View style={styles.suggestionsCard}>
              <Text style={styles.suggestionsTitle}>Improvement Suggestions</Text>
              {qualityResult.suggestions.map((suggestion, index) => (
                <View key={index} style={styles.suggestionItem}>
                  <View style={[styles.suggestionPriority, { backgroundColor: getPriorityColor(suggestion.priority) }]} />
                  <View style={styles.suggestionContent}>
                    <Text style={styles.suggestionTitle}>{suggestion.title}</Text>
                    <Text style={styles.suggestionDescription}>{suggestion.description}</Text>
                    <Text style={styles.suggestionAction}>{suggestion.action}</Text>
                    <View style={styles.suggestionMeta}>
                      <Text style={styles.suggestionMetaText}>
                        {suggestion.difficulty} • {suggestion.timeRequired}
                        {suggestion.automated && ' • Automated'}
                      </Text>
                    </View>
                  </View>
                </View>
              ))}
            </View>
          )}
        </View>
      ) : (
        <View style={styles.placeholder}>
          <ActivityIndicator size="large" color="#FF9800" />
          <Text style={styles.placeholderText}>Assessing quality...</Text>
        </View>
      )}
    </ScrollView>
  );

  const getGradeColor = (grade: string) => {
    switch (grade) {
      case 'A': return '#4CAF50';
      case 'B': return '#8BC34A';
      case 'C': return '#FF9800';
      case 'D': return '#FF5722';
      case 'F': return '#F44336';
      default: return '#666666';
    }
  };

  const getMetricColor = (value: number) => {
    if (value >= 0.8) return '#4CAF50';
    if (value >= 0.6) return '#FF9800';
    return '#F44336';
  };

  const getSeverityColor = (severity: string) => {
    switch (severity) {
      case 'critical': return '#F44336';
      case 'high': return '#FF5722';
      case 'medium': return '#FF9800';
      case 'low': return '#4CAF50';
      default: return '#666666';
    }
  };

  const getPriorityColor = (priority: string) => {
    switch (priority) {
      case 'critical': return '#F44336';
      case 'high': return '#FF5722';
      case 'medium': return '#FF9800';
      case 'low': return '#4CAF50';
      default: return '#666666';
    }
  };

  if (!visible) return null;

  return (
    <View style={styles.container}>
      <LinearGradient
        colors={['rgba(0,0,0,0.9)', 'rgba(0,0,0,0.8)']}
        style={styles.overlay}
      >
        <View style={styles.panel}>
          {/* Header */}
          <View style={styles.header}>
            <View style={styles.headerLeft}>
              <Ionicons name="sparkles" size={24} color="#FFFFFF" />
              <Text style={styles.headerTitle}>AI Enhancements</Text>
            </View>
            <TouchableOpacity style={styles.closeButton} onPress={onClose}>
              <Ionicons name="close" size={24} color="#FFFFFF" />
            </TouchableOpacity>
          </View>

          {/* Processing Status */}
          {isProcessing && (
            <View style={styles.processingStatus}>
              <ActivityIndicator size="small" color="#4CAF50" />
              <Text style={styles.processingText}>{processingStep}</Text>
            </View>
          )}

          {/* Tabs */}
          <View style={styles.tabs}>
            {renderTabButton('cropping', 'crop', 'Auto-Crop')}
            {renderTabButton('classification', 'document-text', 'Classify')}
            {renderTabButton('organization', 'folder', 'Organize')}
            {renderTabButton('quality', 'analytics', 'Quality')}
          </View>

          {/* Tab Content */}
          <View style={styles.tabContainer}>
            {activeTab === 'cropping' && renderCroppingTab()}
            {activeTab === 'classification' && renderClassificationTab()}
            {activeTab === 'organization' && renderOrganizationTab()}
            {activeTab === 'quality' && renderQualityTab()}
          </View>
        </View>
      </LinearGradient>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 1000,
  },
  overlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  panel: {
    width: width * 0.9,
    maxHeight: '80%',
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    overflow: 'hidden',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    backgroundColor: '#2196F3',
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginLeft: 10,
  },
  closeButton: {
    padding: 5,
  },
  processingStatus: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
    backgroundColor: '#E8F5E8',
  },
  processingText: {
    marginLeft: 10,
    fontSize: 14,
    color: '#4CAF50',
    fontWeight: '500',
  },
  tabs: {
    flexDirection: 'row',
    backgroundColor: '#F5F5F5',
  },
  tabButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 15,
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  activeTabButton: {
    borderBottomColor: '#2196F3',
    backgroundColor: '#E3F2FD',
  },
  tabButtonText: {
    marginLeft: 8,
    fontSize: 12,
    color: '#666666',
    fontWeight: '500',
  },
  activeTabButtonText: {
    color: '#2196F3',
    fontWeight: 'bold',
  },
  tabContainer: {
    flex: 1,
  },
  tabContent: {
    flex: 1,
    padding: 20,
  },
  placeholder: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 40,
  },
  placeholderText: {
    marginTop: 15,
    fontSize: 16,
    color: '#666666',
    textAlign: 'center',
  },
  resultHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  resultTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333333',
    marginLeft: 10,
  },
  metricCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 15,
    backgroundColor: '#F8F9FA',
    borderRadius: 10,
    marginBottom: 10,
  },
  metricLabel: {
    fontSize: 14,
    color: '#666666',
  },
  metricValue: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333333',
  },
  gradeCard: {
    alignItems: 'center',
    padding: 20,
    backgroundColor: '#F8F9FA',
    borderRadius: 10,
    marginBottom: 20,
  },
  gradeLabel: {
    fontSize: 14,
    color: '#666666',
    marginBottom: 5,
  },
  gradeValue: {
    fontSize: 48,
    fontWeight: 'bold',
  },
  metricsGrid: {
    marginBottom: 20,
  },
  metricItem: {
    marginBottom: 15,
  },
  metricItemLabel: {
    fontSize: 12,
    color: '#666666',
    marginBottom: 5,
    textTransform: 'capitalize',
  },
  metricBar: {
    height: 8,
    backgroundColor: '#E0E0E0',
    borderRadius: 4,
    overflow: 'hidden',
  },
  metricBarFill: {
    height: '100%',
    borderRadius: 4,
  },
  metricItemValue: {
    fontSize: 12,
    color: '#333333',
    marginTop: 5,
    textAlign: 'right',
  },
  featuresCard: {
    backgroundColor: '#F8F9FA',
    borderRadius: 10,
    padding: 15,
    marginBottom: 15,
  },
  featuresTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333333',
    marginBottom: 10,
  },
  featuresGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  featureItem: {
    width: '50%',
    padding: 5,
  },
  featureLabel: {
    fontSize: 12,
    color: '#666666',
  },
  featureValue: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#333333',
  },
  tagsCard: {
    backgroundColor: '#F8F9FA',
    borderRadius: 10,
    padding: 15,
    marginBottom: 15,
  },
  tagsTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333333',
    marginBottom: 10,
  },
  tagsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  tag: {
    backgroundColor: '#2196F3',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 15,
    marginRight: 8,
    marginBottom: 8,
  },
  tagText: {
    fontSize: 12,
    color: '#FFFFFF',
    fontWeight: '500',
  },
  documentsCard: {
    backgroundColor: '#F8F9FA',
    borderRadius: 10,
    padding: 15,
    marginBottom: 15,
  },
  documentsTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333333',
    marginBottom: 10,
  },
  documentItem: {
    padding: 10,
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    marginBottom: 8,
  },
  documentName: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#333333',
  },
  documentPath: {
    fontSize: 12,
    color: '#666666',
    marginTop: 2,
  },
  documentTags: {
    flexDirection: 'row',
    marginTop: 5,
  },
  documentTag: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
    marginRight: 5,
  },
  documentTagText: {
    fontSize: 10,
    color: '#FFFFFF',
    fontWeight: '500',
  },
  issuesCard: {
    backgroundColor: '#F8F9FA',
    borderRadius: 10,
    padding: 15,
    marginBottom: 15,
  },
  issuesTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333333',
    marginBottom: 10,
  },
  issueItem: {
    flexDirection: 'row',
    padding: 10,
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    marginBottom: 8,
  },
  issueSeverity: {
    width: 4,
    borderRadius: 2,
    marginRight: 10,
  },
  issueContent: {
    flex: 1,
  },
  issueTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#333333',
  },
  issueImpact: {
    fontSize: 12,
    color: '#666666',
    marginTop: 2,
  },
  suggestionsCard: {
    backgroundColor: '#F8F9FA',
    borderRadius: 10,
    padding: 15,
    marginBottom: 15,
  },
  suggestionsTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333333',
    marginBottom: 10,
  },
  suggestionText: {
    fontSize: 14,
    color: '#666666',
    marginBottom: 5,
  },
  suggestionItem: {
    flexDirection: 'row',
    padding: 10,
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    marginBottom: 8,
  },
  suggestionPriority: {
    width: 4,
    borderRadius: 2,
    marginRight: 10,
  },
  suggestionContent: {
    flex: 1,
  },
  suggestionTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#333333',
  },
  suggestionDescription: {
    fontSize: 12,
    color: '#666666',
    marginTop: 2,
  },
  suggestionAction: {
    fontSize: 12,
    color: '#2196F3',
    marginTop: 2,
    fontStyle: 'italic',
  },
  suggestionMeta: {
    marginTop: 5,
  },
  suggestionMetaText: {
    fontSize: 10,
    color: '#999999',
  },
});

export default AIEnhancementsPanel;
