export interface SmartTag {
  id: string;
  name: string;
  category: 'type' | 'content' | 'quality' | 'metadata' | 'context';
  confidence: number;
  autoGenerated: boolean;
  color: string;
}

export interface OrganizationRule {
  id: string;
  name: string;
  description: string;
  conditions: {
    documentType?: string[];
    tags?: string[];
    dateRange?: { start: Date; end: Date };
    qualityScore?: { min: number; max: number };
    customConditions?: any;
  };
  actions: {
    folderPath: string;
    fileName: string;
    additionalTags: string[];
    metadata: Record<string, any>;
  };
  priority: number;
  enabled: boolean;
}

export interface SmartFolder {
  id: string;
  name: string;
  path: string;
  description: string;
  tags: string[];
  documentCount: number;
  lastUpdated: Date;
  autoGenerated: boolean;
  color: string;
}

export interface DocumentMetadata {
  id: string;
  uri: string;
  fileName: string;
  documentType: string;
  tags: SmartTag[];
  qualityScore: number;
  dateCreated: Date;
  dateModified: Date;
  size: number;
  dimensions: { width: number; height: number };
  extractedText?: string;
  customMetadata: Record<string, any>;
  organizationPath: string;
  suggestedActions: string[];
}

export interface OrganizationResult {
  success: boolean;
  organizedDocuments: DocumentMetadata[];
  createdFolders: SmartFolder[];
  appliedRules: OrganizationRule[];
  suggestions: string[];
  errors: string[];
}

export class AISmartOrganization {
  private static instance: AISmartOrganization;
  private organizationRules: Map<string, OrganizationRule> = new Map();
  private smartFolders: Map<string, SmartFolder> = new Map();
  private tagCategories: Map<string, SmartTag[]> = new Map();
  private isInitialized = false;

  static getInstance(): AISmartOrganization {
    if (!AISmartOrganization.instance) {
      AISmartOrganization.instance = new AISmartOrganization();
    }
    return AISmartOrganization.instance;
  }

  private constructor() {
    this.initializeOrganization();
  }

  private initializeOrganization() {
    this.initializeDefaultTags();
    this.initializeDefaultRules();
    this.initializeDefaultFolders();
    this.isInitialized = true;
    console.log('AI Smart Organization initialized');
  }

  private initializeDefaultTags() {
    const defaultTags: SmartTag[] = [
      // Type tags
      { id: 'receipt', name: 'Receipt', category: 'type', confidence: 1.0, autoGenerated: true, color: '#4CAF50' },
      { id: 'invoice', name: 'Invoice', category: 'type', confidence: 1.0, autoGenerated: true, color: '#2196F3' },
      { id: 'contract', name: 'Contract', category: 'type', confidence: 1.0, autoGenerated: true, color: '#FF9800' },
      { id: 'business_card', name: 'Business Card', category: 'type', confidence: 1.0, autoGenerated: true, color: '#9C27B0' },
      { id: 'id_card', name: 'ID Card', category: 'type', confidence: 1.0, autoGenerated: true, color: '#F44336' },
      { id: 'letter', name: 'Letter', category: 'type', confidence: 1.0, autoGenerated: true, color: '#607D8B' },
      
      // Content tags
      { id: 'financial', name: 'Financial', category: 'content', confidence: 1.0, autoGenerated: true, color: '#4CAF50' },
      { id: 'legal', name: 'Legal', category: 'content', confidence: 1.0, autoGenerated: true, color: '#FF9800' },
      { id: 'personal', name: 'Personal', category: 'content', confidence: 1.0, autoGenerated: true, color: '#E91E63' },
      { id: 'business', name: 'Business', category: 'content', confidence: 1.0, autoGenerated: true, color: '#2196F3' },
      { id: 'medical', name: 'Medical', category: 'content', confidence: 1.0, autoGenerated: true, color: '#00BCD4' },
      { id: 'educational', name: 'Educational', category: 'content', confidence: 1.0, autoGenerated: true, color: '#8BC34A' },
      
      // Quality tags
      { id: 'high_quality', name: 'High Quality', category: 'quality', confidence: 1.0, autoGenerated: true, color: '#4CAF50' },
      { id: 'medium_quality', name: 'Medium Quality', category: 'quality', confidence: 1.0, autoGenerated: true, color: '#FF9800' },
      { id: 'low_quality', name: 'Low Quality', category: 'quality', confidence: 1.0, autoGenerated: true, color: '#F44336' },
      { id: 'needs_enhancement', name: 'Needs Enhancement', category: 'quality', confidence: 1.0, autoGenerated: true, color: '#FF5722' },
      
      // Metadata tags
      { id: 'dated', name: 'Dated', category: 'metadata', confidence: 1.0, autoGenerated: true, color: '#795548' },
      { id: 'signed', name: 'Signed', category: 'metadata', confidence: 1.0, autoGenerated: true, color: '#9E9E9E' },
      { id: 'urgent', name: 'Urgent', category: 'metadata', confidence: 1.0, autoGenerated: true, color: '#F44336' },
      { id: 'archived', name: 'Archived', category: 'metadata', confidence: 1.0, autoGenerated: true, color: '#607D8B' },
      
      // Context tags
      { id: 'work', name: 'Work', category: 'context', confidence: 1.0, autoGenerated: true, color: '#2196F3' },
      { id: 'personal', name: 'Personal', category: 'context', confidence: 1.0, autoGenerated: true, color: '#E91E63' },
      { id: 'tax', name: 'Tax', category: 'context', confidence: 1.0, autoGenerated: true, color: '#4CAF50' },
      { id: 'insurance', name: 'Insurance', category: 'context', confidence: 1.0, autoGenerated: true, color: '#FF9800' }
    ];

    // Group tags by category
    defaultTags.forEach(tag => {
      if (!this.tagCategories.has(tag.category)) {
        this.tagCategories.set(tag.category, []);
      }
      this.tagCategories.get(tag.category)!.push(tag);
    });
  }

  private initializeDefaultRules() {
    const defaultRules: OrganizationRule[] = [
      {
        id: 'receipts_rule',
        name: 'Organize Receipts',
        description: 'Automatically organize receipts by date and store',
        conditions: {
          documentType: ['receipt'],
          tags: ['financial']
        },
        actions: {
          folderPath: '/Receipts/{year}/{month}',
          fileName: 'Receipt_{date}_{store}',
          additionalTags: ['financial', 'dated'],
          metadata: { autoOrganized: true, category: 'expenses' }
        },
        priority: 1,
        enabled: true
      },
      {
        id: 'contracts_rule',
        name: 'Organize Contracts',
        description: 'Automatically organize contracts by type and date',
        conditions: {
          documentType: ['contract'],
          tags: ['legal']
        },
        actions: {
          folderPath: '/Contracts/{year}',
          fileName: 'Contract_{type}_{date}',
          additionalTags: ['legal', 'signed'],
          metadata: { autoOrganized: true, category: 'legal' }
        },
        priority: 2,
        enabled: true
      },
      {
        id: 'business_cards_rule',
        name: 'Organize Business Cards',
        description: 'Automatically organize business cards by company',
        conditions: {
          documentType: ['business_card'],
          tags: ['business']
        },
        actions: {
          folderPath: '/Business Cards/{company}',
          fileName: 'BusinessCard_{name}_{company}',
          additionalTags: ['business', 'contact'],
          metadata: { autoOrganized: true, category: 'contacts' }
        },
        priority: 3,
        enabled: true
      },
      {
        id: 'id_documents_rule',
        name: 'Organize ID Documents',
        description: 'Automatically organize ID documents securely',
        conditions: {
          documentType: ['id_card', 'passport'],
          tags: ['personal']
        },
        actions: {
          folderPath: '/Personal/ID Documents',
          fileName: 'ID_{type}_{date}',
          additionalTags: ['personal', 'secure'],
          metadata: { autoOrganized: true, category: 'personal', secure: true }
        },
        priority: 4,
        enabled: true
      },
      {
        id: 'high_quality_rule',
        name: 'Archive High Quality Documents',
        description: 'Move high quality documents to archive',
        conditions: {
          qualityScore: { min: 0.9, max: 1.0 }
        },
        actions: {
          folderPath: '/Archive/High Quality',
          fileName: '{originalName}',
          additionalTags: ['archived', 'high_quality'],
          metadata: { autoOrganized: true, category: 'archive' }
        },
        priority: 5,
        enabled: true
      }
    ];

    defaultRules.forEach(rule => {
      this.organizationRules.set(rule.id, rule);
    });
  }

  private initializeDefaultFolders() {
    const defaultFolders: SmartFolder[] = [
      {
        id: 'receipts_folder',
        name: 'Receipts',
        path: '/Receipts',
        description: 'All receipt documents organized by date',
        tags: ['financial', 'receipts'],
        documentCount: 0,
        lastUpdated: new Date(),
        autoGenerated: true,
        color: '#4CAF50'
      },
      {
        id: 'contracts_folder',
        name: 'Contracts',
        path: '/Contracts',
        description: 'Legal documents and contracts',
        tags: ['legal', 'contracts'],
        documentCount: 0,
        lastUpdated: new Date(),
        autoGenerated: true,
        color: '#FF9800'
      },
      {
        id: 'business_cards_folder',
        name: 'Business Cards',
        path: '/Business Cards',
        description: 'Contact information and business cards',
        tags: ['business', 'contacts'],
        documentCount: 0,
        lastUpdated: new Date(),
        autoGenerated: true,
        color: '#9C27B0'
      },
      {
        id: 'personal_folder',
        name: 'Personal',
        path: '/Personal',
        description: 'Personal documents and ID cards',
        tags: ['personal', 'private'],
        documentCount: 0,
        lastUpdated: new Date(),
        autoGenerated: true,
        color: '#E91E63'
      },
      {
        id: 'archive_folder',
        name: 'Archive',
        path: '/Archive',
        description: 'Archived and high-quality documents',
        tags: ['archived', 'high_quality'],
        documentCount: 0,
        lastUpdated: new Date(),
        autoGenerated: true,
        color: '#607D8B'
      }
    ];

    defaultFolders.forEach(folder => {
      this.smartFolders.set(folder.id, folder);
    });
  }

  async organizeDocuments(documents: DocumentMetadata[]): Promise<OrganizationResult> {
    try {
      const organizedDocuments: DocumentMetadata[] = [];
      const createdFolders: SmartFolder[] = [];
      const appliedRules: OrganizationRule[] = [];
      const suggestions: string[] = [];
      const errors: string[] = [];

      for (const document of documents) {
        try {
          // Generate AI tags for the document
          const aiTags = await this.generateAITags(document);
          document.tags = [...document.tags, ...aiTags];

          // Find applicable organization rules
          const applicableRules = this.findApplicableRules(document);

          if (applicableRules.length > 0) {
            // Apply the highest priority rule
            const rule = applicableRules[0];
            const organizedDoc = await this.applyOrganizationRule(document, rule);
            organizedDocuments.push(organizedDoc);
            appliedRules.push(rule);

            // Create folder if it doesn't exist
            const folder = await this.ensureFolderExists(rule.actions.folderPath);
            if (folder && !createdFolders.find(f => f.id === folder.id)) {
              createdFolders.push(folder);
            }
          } else {
            // No rules apply, suggest manual organization
            document.suggestedActions.push('No automatic organization rule found. Consider manual organization.');
            organizedDocuments.push(document);
          }

          // Generate suggestions based on document analysis
          const docSuggestions = this.generateDocumentSuggestions(document);
          suggestions.push(...docSuggestions);

        } catch (error) {
          console.error(`Failed to organize document ${document.id}:`, error);
          errors.push(`Failed to organize document ${document.fileName}: ${error}`);
          organizedDocuments.push(document);
        }
      }

      return {
        success: errors.length === 0,
        organizedDocuments,
        createdFolders,
        appliedRules,
        suggestions: [...new Set(suggestions)],
        errors
      };

    } catch (error) {
      console.error('Document organization failed:', error);
      return {
        success: false,
        organizedDocuments: documents,
        createdFolders: [],
        appliedRules: [],
        suggestions: ['Organization failed. Please try again.'],
        errors: [`Organization failed: ${error}`]
      };
    }
  }

  private async generateAITags(document: DocumentMetadata): Promise<SmartTag[]> {
    const aiTags: SmartTag[] = [];

    // Analyze document type
    if (document.documentType) {
      const typeTag = this.findTagByName(document.documentType);
      if (typeTag) {
        aiTags.push({ ...typeTag, confidence: 0.9 });
      }
    }

    // Analyze quality
    if (document.qualityScore >= 0.9) {
      aiTags.push({ ...this.findTagByName('high_quality')!, confidence: document.qualityScore });
    } else if (document.qualityScore >= 0.7) {
      aiTags.push({ ...this.findTagByName('medium_quality')!, confidence: document.qualityScore });
    } else {
      aiTags.push({ ...this.findTagByName('low_quality')!, confidence: document.qualityScore });
    }

    // Analyze content
    if (document.extractedText) {
      const text = document.extractedText.toLowerCase();
      
      if (this.containsFinancialContent(text)) {
        aiTags.push({ ...this.findTagByName('financial')!, confidence: 0.8 });
      }
      
      if (this.containsLegalContent(text)) {
        aiTags.push({ ...this.findTagByName('legal')!, confidence: 0.8 });
      }
      
      if (this.containsPersonalInfo(text)) {
        aiTags.push({ ...this.findTagByName('personal')!, confidence: 0.9 });
      }
      
      if (this.containsBusinessContent(text)) {
        aiTags.push({ ...this.findTagByName('business')!, confidence: 0.8 });
      }
    }

    // Analyze metadata
    if (document.dateCreated) {
      aiTags.push({ ...this.findTagByName('dated')!, confidence: 1.0 });
    }

    // Analyze context
    if (document.customMetadata.workRelated) {
      aiTags.push({ ...this.findTagByName('work')!, confidence: 0.9 });
    } else {
      aiTags.push({ ...this.findTagByName('personal')!, confidence: 0.7 });
    }

    return aiTags.filter(tag => tag !== undefined);
  }

  private containsFinancialContent(text: string): boolean {
    const financialKeywords = ['invoice', 'receipt', 'payment', 'amount', 'total', 'price', 'cost', 'expense', 'budget'];
    return financialKeywords.some(keyword => text.includes(keyword));
  }

  private containsLegalContent(text: string): boolean {
    const legalKeywords = ['contract', 'agreement', 'terms', 'conditions', 'legal', 'liability', 'warranty', 'signature'];
    return legalKeywords.some(keyword => text.includes(keyword));
  }

  private containsPersonalInfo(text: string): boolean {
    const personalPatterns = [
      /\b[A-Z][a-z]+\s+[A-Z][a-z]+\b/, // Name pattern
      /\b\d{3}-\d{2}-\d{4}\b/,         // SSN pattern
      /\b\d{3}-\d{3}-\d{4}\b/,         // Phone pattern
      /\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b/ // Email pattern
    ];
    return personalPatterns.some(pattern => pattern.test(text));
  }

  private containsBusinessContent(text: string): boolean {
    const businessKeywords = ['company', 'corp', 'inc', 'llc', 'business', 'office', 'department', 'manager', 'director'];
    return businessKeywords.some(keyword => text.includes(keyword));
  }

  private findApplicableRules(document: DocumentMetadata): OrganizationRule[] {
    const applicableRules: OrganizationRule[] = [];

    for (const rule of this.organizationRules.values()) {
      if (!rule.enabled) continue;

      let matches = true;

      // Check document type condition
      if (rule.conditions.documentType && rule.conditions.documentType.length > 0) {
        matches = matches && rule.conditions.documentType.includes(document.documentType);
      }

      // Check tags condition
      if (rule.conditions.tags && rule.conditions.tags.length > 0) {
        const documentTagNames = document.tags.map(tag => tag.name.toLowerCase());
        matches = matches && rule.conditions.tags.some(tag => 
          documentTagNames.includes(tag.toLowerCase())
        );
      }

      // Check quality score condition
      if (rule.conditions.qualityScore) {
        const { min, max } = rule.conditions.qualityScore;
        matches = matches && document.qualityScore >= min && document.qualityScore <= max;
      }

      // Check date range condition
      if (rule.conditions.dateRange) {
        const { start, end } = rule.conditions.dateRange;
        matches = matches && document.dateCreated >= start && document.dateCreated <= end;
      }

      if (matches) {
        applicableRules.push(rule);
      }
    }

    // Sort by priority (lower number = higher priority)
    return applicableRules.sort((a, b) => a.priority - b.priority);
  }

  private async applyOrganizationRule(document: DocumentMetadata, rule: OrganizationRule): Promise<DocumentMetadata> {
    const organizedDoc = { ...document };

    // Apply folder path
    organizedDoc.organizationPath = this.processPathTemplate(rule.actions.folderPath, document);

    // Apply file name
    organizedDoc.fileName = this.processPathTemplate(rule.actions.fileName, document);

    // Add additional tags
    const additionalTags = rule.actions.additionalTags.map(tagName => {
      const tag = this.findTagByName(tagName);
      return tag ? { ...tag, confidence: 0.8 } : null;
    }).filter(tag => tag !== null) as SmartTag[];

    organizedDoc.tags = [...organizedDoc.tags, ...additionalTags];

    // Add metadata
    organizedDoc.customMetadata = {
      ...organizedDoc.customMetadata,
      ...rule.actions.metadata
    };

    return organizedDoc;
  }

  private processPathTemplate(template: string, document: DocumentMetadata): string {
    let processed = template;

    // Replace placeholders
    processed = processed.replace(/{year}/g, document.dateCreated.getFullYear().toString());
    processed = processed.replace(/{month}/g, (document.dateCreated.getMonth() + 1).toString().padStart(2, '0'));
    processed = processed.replace(/{date}/g, document.dateCreated.toISOString().split('T')[0]);
    processed = processed.replace(/{type}/g, document.documentType);
    processed = processed.replace(/{originalName}/g, document.fileName);

    // Extract company name from tags or metadata
    const companyTag = document.tags.find(tag => tag.category === 'content' && tag.name.toLowerCase().includes('company'));
    if (companyTag) {
      processed = processed.replace(/{company}/g, companyTag.name);
    }

    // Extract person name from metadata
    if (document.customMetadata.personName) {
      processed = processed.replace(/{name}/g, document.customMetadata.personName);
    }

    return processed;
  }

  private async ensureFolderExists(folderPath: string): Promise<SmartFolder | null> {
    // Check if folder already exists
    const existingFolder = Array.from(this.smartFolders.values())
      .find(folder => folder.path === folderPath);

    if (existingFolder) {
      return existingFolder;
    }

    // Create new folder
    const newFolder: SmartFolder = {
      id: `folder_${Date.now()}_${Math.random()}`,
      name: folderPath.split('/').pop() || 'New Folder',
      path: folderPath,
      description: `Auto-generated folder: ${folderPath}`,
      tags: ['auto-generated'],
      documentCount: 0,
      lastUpdated: new Date(),
      autoGenerated: true,
      color: '#9E9E9E'
    };

    this.smartFolders.set(newFolder.id, newFolder);
    return newFolder;
  }

  private generateDocumentSuggestions(document: DocumentMetadata): string[] {
    const suggestions: string[] = [];

    if (document.qualityScore < 0.7) {
      suggestions.push(`Document "${document.fileName}" has low quality. Consider rescanning for better results.`);
    }

    if (document.tags.length < 3) {
      suggestions.push(`Document "${document.fileName}" has few tags. Consider adding more descriptive tags.`);
    }

    if (document.extractedText && document.extractedText.length < 50) {
      suggestions.push(`Document "${document.fileName}" has minimal text. Ensure all text is clearly visible.`);
    }

    if (document.customMetadata.urgent) {
      suggestions.push(`Document "${document.fileName}" is marked as urgent. Consider prioritizing its organization.`);
    }

    return suggestions;
  }

  private findTagByName(name: string): SmartTag | undefined {
    for (const tags of this.tagCategories.values()) {
      const tag = tags.find(t => t.name.toLowerCase() === name.toLowerCase());
      if (tag) return tag;
    }
    return undefined;
  }

  // Public methods for managing organization
  addOrganizationRule(rule: OrganizationRule): void {
    this.organizationRules.set(rule.id, rule);
  }

  updateOrganizationRule(ruleId: string, updates: Partial<OrganizationRule>): void {
    const rule = this.organizationRules.get(ruleId);
    if (rule) {
      Object.assign(rule, updates);
      this.organizationRules.set(ruleId, rule);
    }
  }

  deleteOrganizationRule(ruleId: string): void {
    this.organizationRules.delete(ruleId);
  }

  getOrganizationRules(): OrganizationRule[] {
    return Array.from(this.organizationRules.values());
  }

  getSmartFolders(): SmartFolder[] {
    return Array.from(this.smartFolders.values());
  }

  getTagsByCategory(category: string): SmartTag[] {
    return this.tagCategories.get(category) || [];
  }

  getAllTags(): SmartTag[] {
    const allTags: SmartTag[] = [];
    for (const tags of this.tagCategories.values()) {
      allTags.push(...tags);
    }
    return allTags;
  }

  isReady(): boolean {
    return this.isInitialized;
  }
}
